#!/usr/bin/env bash

set -euo pipefail

if [ -d "$HOME/.oh-my-zsh" ]; then
  printf 'Oh My Zsh already installed\n'
else
  printf 'Installing Oh My Zsh...\n'
  RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  printf 'Oh My Zsh installed\n'
fi

if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]; then
  printf 'Installing zsh-autosuggestions plugin...\n'
  git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
fi
